package com.jacobs.mj.neemnotas.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)

val md_theme_light_primary = Color(0xFF004dec)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdbe1ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001552)
val md_theme_light_secondary = Color(0xFF006e0b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF72ff6f)
val md_theme_light_onSecondaryContainer = Color(0xFF002201)
val md_theme_light_tertiary = Color(0xFF74546f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd7f7)
val md_theme_light_onTertiaryContainer = Color(0xFF2c122a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFe2e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF45464e)
val md_theme_light_outline = Color(0xFF76767f)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFFb4c4ff)
val md_theme_dark_onPrimary = Color(0xFF002682)
val md_theme_dark_primaryContainer = Color(0xFF0039b6)
val md_theme_dark_onPrimaryContainer = Color(0xFFdbe1ff)
val md_theme_dark_secondary = Color(0xFF36e442)
val md_theme_dark_onSecondary = Color(0xFF003a02)
val md_theme_dark_secondaryContainer = Color(0xFF005306)
val md_theme_dark_onSecondaryContainer = Color(0xFF72ff6f)
val md_theme_dark_tertiary = Color(0xFFe3bada)
val md_theme_dark_onTertiary = Color(0xFF432740)
val md_theme_dark_tertiaryContainer = Color(0xFF5b3d57)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd7f7)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF45464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c6d0)
val md_theme_dark_outline = Color(0xFF90909a)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF1a5eff)
val error = Color(0xFFba1b1b)